version: "3.7"

services:
  # redis:
  #   image: redis:latest
  #   container_name: eventr_redis
  #   ports:
  #     - "6379:6379"
  #   restart: on-failure
  postgres:
    image: postgres:latest
    container_name: eventr-postgres
    environment:
      POSTGRES_DATABASE: eventr-base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    restart: on-failure
