// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: artist.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

type AddArtistsQueryParams struct {
	EventID  uuid.UUID
	Username string
}

const verifyArtistQuery = `-- name: VerifyArtistQuery :exec
SELECT
    username
FROM
    user_account
WHERE
    username = ANY ($1::varchar[])
`

func (q *Queries) VerifyArtistQuery(ctx context.Context, db DBTX, dollar_1 []string) error {
	_, err := db.Exec(ctx, verifyArtistQuery, dollar_1)
	return err
}
